[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"

]
edition = "2018"
name = "blinky"
version = "0.1.0"
description = "Raspberry Pi Pico Blinky"
keywords = ["rp", "rpi", "pico", "blinky", "basic"]

[dependencies]
defmt = "0.3"
defmt-rtt = "0.3"
panic-probe = { version = "0.3", features = ["print-defmt"] }
drogue-device = { path = "../../../../device", features = ["defmt"], default-features = false }
ector = { version = "0.1.0", default-features = false }
atomic-polyfill = { version = "0.1" }
embedded-hal = { version = "0.2.4", features = ["unproven"] }
rp2040-pac = { version = "0.1.4", features = ["rt"] }

cortex-m-rt = "0.7"
cortex-m = { version = "0.7", features = ["inline-asm"] }

embassy-executor = { version = "0.1.0", default-features = false }
embassy-rp = { version = "0.1.0", default-features = false }
