[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>",
    "Jens Reimann <jreimann@redhat.com>",
    "Dejan Bosanac <dbosanac@redhat.com>"
]
edition = "2018"
name = "drogue-blinky-app"
version = "0.1.0"
description = "BSP Blinky App"
keywords = ["ignore"]

[dependencies]
defmt = "0.3"
drogue-device = { path = "../../../device", default-features = false }
ector = { version = "0.1.0", default-features = false }
embassy-executor = { version = "0.1.0", default-features = false }
#, features=["defmt", "time", "time-tick-32768hz"] }
