[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "adafruit-feather-nrf52840-bootloader-dfu"
version = "0.1.0"
description = "Adafruit Feather nRF52840 Bootloader DFU example"
keywords = ["nrf52840", "nrf", "nrf52", "dfu", "bootloader", "feather", "adafruit", "ble"]
resolver = "2"

[dependencies]
defmt = { version = "0.3" }
panic-probe = { version = "0.3", features = ["print-defmt"], optional = true }
panic-reset = { version = "0.1.1", optional = true }

drogue-device = { path = "../../../../../device", default-features = false, features = ["time", "dfu", "bsp+adafruit_feather_nrf52840", "ble+nrf52840"] }

embassy-boot-nrf = { version = "0.1.0", default-features = false, features = ["softdevice"] }
embassy = { version = "0.1.0", default-features = false, features = [] }
embassy-nrf = { version = "0.1.0", default-features = false, features = ["nrf52840", "gpiote", "time-driver-rtc1"]}

cortex-m    = "0.7"
cortex-m-rt = "0.7"
heapless = "0.7"
futures     = { version = "0.3.17", default-features = false, features = ["async-await"] }

nrf-softdevice = { version = "0.1.0", features = ["ble-peripheral", "ble-gatt-server", "s140", "nrf52840", "critical-section-impl"] }
nrf-softdevice-s140 = { version = "0.1.0" }
nrf-softdevice-defmt-rtt = { version = "0.1.0", optional = true }

[features]
default = [
    "panic-reset"
]
debug = [
    "panic-probe",
    "drogue-device/defmt",
    "nrf-softdevice/defmt",
    "embassy/defmt",
    "embassy-nrf/defmt",
    "embassy-boot-nrf/defmt",
    "nrf-softdevice-defmt-rtt",
]
