[package]
name = "drogue-esp8266"
version = "0.1.0"
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
license = "Apache-2.0"
description = "Async driver implementing drogue-network API for ESP8266 AT-firmware"
readme = "README.md"
repository = "https://github.com/drogue-iot/drogue-device"
homepage = "https://blog.drogue.io"
categories = ["embedded", "no-std", "network-programming"]
keywords = ["driver", "network", "lora", "no_std", "tcp", "ip", "esp8266"]

[dependencies]
drogue-device-kernel = { path = "../../../kernel" }
drogue-network = { path = "../../../traits/network" }

embassy = {git = "https://github.com/drogue-iot/embassy.git", branch = "drogue", default-features = false } #, path = "../../../embassy/embassy" }

heapless = "0.5"
moveslice = "2.0"
futures = { version = "0.3", default-features = false }
nom = { version = "6.1.2", default-features = false }
embedded-hal = { version = "0.2.4", features = ["unproven"] }
log = { version = "0.4", optional = true }
defmt = { version = "0.2", optional = true }

[dev-dependencies]
arrayvec = "0.5"

[features]
defmt-default = []
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
