[package]
edition = "2021"
name = "nucleo-h743zi_ethernet"
version = "0.1.0"
resolver = "2"
description = "STM32 Nucleo-H743 ethernet"
keywords = ["ethernet", "stm32", "stm32h7", "networking"]

[dependencies]
defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }

static_cell = "1"
embedded-hal = { version = "0.2.4", features = ["unproven"] }
drogue-device = { path = "../../../../device", features = ["defmt"], default-features = false }
ector = { version = "0.1.0", default-features = false }
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = { version = "0.7" }
heapless = "0.7"
void = { version = "1", default-features = false }
critical-section = "0.2.5"
rand_core = "0.6.3"
reqwless = { version = "0.5", default-features = false }
embedded-nal-async = "0.4.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-json-core = { version = "0.4", default-features = false, features = ["heapless"] }

embassy-executor = { version = "0.1.0", default-features = false, features = ["integrated-timers"] }
embassy-time = { version = "0.1.0", default-features = false }
embassy-stm32 = { version = "0.1.0", default-features = false, features = ["stm32h743zi", "defmt", "memory-x", "time-driver-any", "unstable-traits", "unstable-pac", "nightly"] }
embassy-net = { version = "0.1.0", default-features = false, features = ["defmt", "nightly", "unstable-traits", "dns"] }
nucleo-h743zi = { path = "../../../../boards/nucleo-h743zi" } 
