[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "lorawan"
version = "0.1.0"
resolver = "2"
description = "STM32 Nucleo-WL55 using LoRaWAN connecting to The Things Network"
keywords = ["lorawan", "lora", "stm32wl", "stm32wl55", "networking", "iot", "stm32"]

[dependencies]
embedded-hal = { version = "0.2.4", features = ["unproven"] }

defmt = "0.3"
defmt-rtt = "0.3"
panic-probe = { version = "0.3", features = ["print-defmt"] }

drogue-lorawan-app = { path = "../../../apps/lorawan" }
drogue-device = { path = "../../../../device", features = ["lora", "defmt", "bsp+nucleo_wl55"], default-features = false }
cortex-m-rt = ">=0.6.15,<0.8" #"0.7"
cortex-m = { version = "0.7", features = ["inline-asm"] }
heapless = "0.7"
void = { version = "1", default-features = false }
rand_core = { version = "0.6", default-features = false }

embassy-executor = { version = "0.1.0", default-features = false, features = ["time-tick-32768hz"] }
embassy-lora = { version = "0.1.0", default-features = false, features = ["stm32wl"] }
embassy-stm32 = { version = "0.1.0", default-features = false, features = ["defmt", "stm32wl55jc-cm4", "time-driver-any", "unstable-pac", "subghz"] }
