[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
]
edition = "2018"
name = "ble"
version = "0.1.0"
description = "Bluetooth Low Energy (BLE) GATT services and actors"
keywords = ["ignore"]

[workspace]

[dependencies]
drogue-device = { path = "../../../device", default-features = false }
heapless = "0.7"
futures     = { version = "0.3.17", default-features = false, features = ["async-await"] }

embassy = { version = "0.1.0", default-features = false, features = ["time"] }
fixed = "1.5.0"

nrf-softdevice = { version = "0.1.0", features = ["ble-peripheral", "ble-gatt-server"] }
nrf-softdevice-s113 = { version = "0.1.0", optional = true }

#nrf-softdevice = { version = "0.1.0", path = "../../../../nrf-softdevice/nrf-softdevice", features = ["ble-peripheral", "critical-section-impl", "ble-gatt-server"] }
#nrf-softdevice-s113 = { version = "0.1.0", path = "../../../../nrf-softdevice/nrf-softdevice-s113", optional = true }

defmt = { version = "0.3", optional = true }
log = { version = "0.4", optional = true }

[features]
s113 = ["nrf-softdevice-s113", "nrf-softdevice/s113"]
nrf52833 = ["nrf-softdevice/nrf52833"]
withdefmt = ["nrf-softdevice/defmt"]

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "6a3b3ca755073f73b24fad89a109fba7132d1312" }
nrf-softdevice = { git = "https://github.com/embassy-rs/nrf-softdevice.git", rev = "c584deaf9d9e941f18457934a4a463e078f380ec" }
nrf-softdevice-s113 = { git = "https://github.com/embassy-rs/nrf-softdevice.git", rev = "c584deaf9d9e941f18457934a4a463e078f380ec" }
#embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "6a3b3ca755073f73b24fad89a109fba7132d1312" }
#embassy-lora = { git = "https://github.com/embassy-rs/embassy.git", rev = "6a3b3ca755073f73b24fad89a109fba7132d1312" }
#embassy-net = { git = "https://github.com/embassy-rs/embassy.git", rev = "6a3b3ca755073f73b24fad89a109fba7132d1312" }
