[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>",
    "Jens Reimann <jreimann@redhat.com>",
    "Dejan Bosanac <dbosanac@redhat.com>"
]
edition = "2018"
name = "adafruit-feather-53840-sense-blinky"
version = "0.1.0"
description = "Adafruit Feather nRF52840 Sense blinky"
keywords = ["adafruit", "feather", "nrf", "nrf52", "blinky"]
resolver = "2"

[dependencies]

defmt = "0.3"
defmt-rtt = "0.3"
panic-probe = { version = "0.3", features = ["print-defmt"] }
cortex-m-rt = "0.7.0"
cortex-m = "0.7.1"
#cfg-if = "1.0.0"

bsp-blinky-app = { path = "../../../apps/blinky" }
embedded-hal = { version = "0.2.4", features = ["unproven"] }

drogue-device = { path = "../../../../device", default-features = false, features = [ "bsp+adafruit_feather_nrf52840_sense" ] }
embassy = { version = "0.1.0", default-features = false, features=["defmt", "time"] }
embassy-nrf = { version = "0.1.0", default-features = false, features = ["nrf52840", "time-driver-rtc1", "gpiote"]}
