[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>",
    "Jens Reimann <jreimann@redhat.com>",
    "Dejan Bosanac <dbosanac@redhat.com>"
]
edition = "2018"
name = "lorawan-app"
version = "0.1.0"
description = "LoRaWAN App"
keywords = ["ignore"]

[workspace]

[dependencies]
defmt = "0.3"
drogue-device = { path = "../../../device", default-features = false, features = ["lora", "time", "defmt"] }
embassy = { version = "0.1.0", default-features = false, features = ["time"] }
heapless = "0.7"

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "da9c0efaad594b48cfcdf641d353133d14cf98fe" }
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "da9c0efaad594b48cfcdf641d353133d14cf98fe" }
embassy-lora = { git = "https://github.com/embassy-rs/embassy.git", rev = "da9c0efaad594b48cfcdf641d353133d14cf98fe" }
