[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "microbit-rak811"
version = "0.1.0"

[workspace]

[dependencies]
panic-probe = { version = "0.2.0", features = ["print-rtt"] }
log = "0.4"
rtt-logger = "0.1"
rtt-target = { version = "0.2.0", features = ["cortex-m"] }

drogue-device = { path = "../../../device", features = ["lora+rak811"], default-features = false }
cortex-m-rt = "0.6"
cortex-m = { version = "0.6", features = ["inline-asm"] }

embassy = {git = "https://github.com/embassy-rs/embassy.git", rev = "0a1da180d0fd93deaf9cc453566c3d66511c03a8", default-features = false}
embassy-nrf = {git = "https://github.com/embassy-rs/embassy.git", rev = "0a1da180d0fd93deaf9cc453566c3d66511c03a8", default-features = false, features = ["nrf52833"]}
#embassy = {path = "../../../../../embassy/embassy", default-features = false}
#embassy-nrf = {path = "../../../../../embassy/embassy-nrf", default-features = false, features = ["nrf52833"]}

[patch.crates-io]
cortex-m = {git = "https://github.com/rust-embedded/cortex-m.git", branch = "master", features = ["device"]}
