[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "nrf52840-ble-mesh"
version = "0.1.0"
description = "nrf52840-dk BLE Mesh example"
keywords = ["ble", "bluetooth", "microbit", "nrf", "nrf52", "temperature"]
resolver = "2"

[workspace]

[dependencies]
defmt = { version = "0.3" }
defmt-rtt = { version = "0.3", optional = true }
panic-probe = { version = "0.3", features = ["print-defmt"] }

drogue-device = { path = "../../../../device", default-features = false, features = ["defmt", "time", "bsp+microbit", "ble+nrf52840", "ble-mesh-relay"] }

embassy = { version = "0.1.0", default-features = false, features = [] }
embassy-nrf = { version = "0.1.0", default-features = false, features = ["nrf52840", "gpiote", "time-driver-rtc1"]}

cortex-m        = { version = "0.7.2" }
cortex-m-rt = "0.7"
heapless = "0.7"
futures     = { version = "0.3.17", default-features = false, features = ["async-await"] }

nrf-softdevice = { version = "0.1.0", features = ["ble-peripheral", "ble-central", "ble-gatt-server", "s140", "nrf52840", "defmt", "critical-section-impl" ] }
nrf-softdevice-s140 = { version = "0.1.0" }
# Bluetooth app
#ble = { path = "../../../apps/ble", features = ["nrf52833", "s113"] }

[features]
default = [
    "defmt-rtt",
    "drogue-device/defmt",
    "embassy/defmt",
    "embassy-nrf/defmt",
#    "ble/defmt",
#    "ble/withdefmt",
]

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
#lto = "fat"
opt-level = 1
overflow-checks = false

# do not optimize proc-macro crates = faster builds from scratch
[profile.dev.build-override]
codegen-units = 8
debug = 2
debug-assertions = false
opt-level = 0
overflow-checks = false

[profile.release.build-override]
codegen-units = 8
debug = 2
debug-assertions = false
opt-level = 1 
overflow-checks = false

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "36a1f203648dcb402727ea3eb5d30cf1f6993795" }
embassy-nrf = { git = "https://github.com/embassy-rs/embassy.git", rev = "36a1f203648dcb402727ea3eb5d30cf1f6993795" }
nrf-softdevice = { git = "https://github.com/embassy-rs/nrf-softdevice/", rev = "a5026485151138112b522a27c4a340614d7a7512" }
nrf-softdevice-s140 = { git = "https://github.com/embassy-rs/nrf-softdevice/", rev = "a5026485151138112b522a27c4a340614d7a7512" }
nrf-softdevice-macro = { git = "https://github.com/embassy-rs/nrf-softdevice/", rev = "a5026485151138112b522a27c4a340614d7a7512" }

#embassy = { path = "../../../../../../embassy/embassy" }
#embassy-nrf = { path = "../../../../../../embassy/embassy-nrf" }
