[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "nrf52840-ble-mesh"
version = "0.1.0"
description = "nrf52840-dk BLE Mesh example"
keywords = ["ble", "bluetooth", "microbit", "nrf", "nrf52", "temperature"]

[dependencies]
defmt = { version = "0.3" }
defmt-rtt = { version = "0.3", optional = true }
panic-probe = { version = "0.3", features = ["print-defmt"] }

drogue-device = { path = "../../../../device", default-features = false, features = ["defmt", "time", "bsp+microbit", "ble+nrf52840"] }

embassy = { version = "0.1.0", default-features = false, features = [] }
embassy-nrf = { version = "0.1.0", default-features = false, features = ["nrf52840", "gpiote", "time-driver-rtc1"]}

cortex-m        = { version = "0.7.2" }
cortex-m-rt = "0.6"
heapless = "0.7"
futures     = { version = "0.3.17", default-features = false, features = ["async-await"] }

nrf-softdevice = { version = "0.1.0", features = ["ble-peripheral", "ble-central", "ble-gatt-server", "s140", "nrf52840"] }
nrf-softdevice-s140 = { version = "0.1.0" }
# Bluetooth app
#ble = { path = "../../../apps/ble", features = ["nrf52833", "s113"] }

[features]
default = [
    "defmt-rtt",
    "drogue-device/defmt",
    "embassy/defmt",
    "embassy-nrf/defmt",
#    "ble/defmt",
#    "ble/withdefmt",
]
