[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>",
    "Jens Reimann <jreimann@redhat.com>",
    "Dejan Bosanac <dbosanac@redhat.com>"
]
edition = "2018"
name = "iot01a-wifi"
version = "0.1.0"
resolver = "2"
description = "STM32 IoT Discovery board (iot01a) reporting sensor data using WiFi"
keywords = ["wifi", "hts221", "stm32l4", "networking", "iot", "stm32", "cloud"]

[workspace]

[dependencies]
defmt = "0.3"
defmt-rtt = "0.3"
panic-probe = { version = "0.3", features = ["print-defmt"] }

drogue-device = { path = "../../../device", default-features = false, features = ["defmt", "time", "wifi+eswifi"] }
cortex-m-rt = "0.7.0"
# cortex-m = { version = "0.7", features = ["inline-asm"] }
cortex-m = "0.7"


# embassy = { git = "https://github.com/drogue-iot/embassy.git", branch = "master", default-features = false, features=["defmt"] }
# embassy-stm32 = { git = "https://github.com/drogue-iot/embassy.git", branch = "master", default-features = false, features = ["defmt", "stm32l432kc"] }
drogue-tls = { version = "0.5.0", default-features = false, features = ["async", "defmt"], optional = true}
# drogue-tls = {path = "../../../../drogue-tls", default-features = false, features = ["async", "defmt"], optional = true}
cfg-if = "1.0.0"

atomic-polyfill = "0.1"
embassy = { version = "0.1.0", default-features = false, features=["defmt", "time", "time-tick-32768hz"] }
embassy-stm32 = {version = "0.1.0", default-features = false, features = ["defmt", "time-driver-tim2", "memory-x"] }
drogue-temperature = { path = "../../apps/temperature", features = ["defmt"], default-features = false }

embedded-hal = { version = "0.2.4", features = ["unproven"] }

[features]
default = [
    "b-l4s5i-iot01a",
]
tls = ["drogue-tls", "drogue-tls/defmt", "drogue-device/tls", "drogue-temperature/tls"]
b-l4s5i-iot01a = ["embassy-stm32/stm32l4s5vi", "drogue-device/bsp+b_l4s5i_iot01a"]
b-l475e-iot01a = ["embassy-stm32/stm32l475vg", "drogue-device/bsp+b_l475e_iot01a"]

[patch.crates-io]
embassy = {git = "https://github.com/embassy-rs/embassy.git", rev = "ac3986e40ef297b90de19812aebccfe2e7f9ceec" }
embassy-stm32 = {git = "https://github.com/embassy-rs/embassy.git", rev = "ac3986e40ef297b90de19812aebccfe2e7f9ceec" }

#embassy = { path = "../../../../../embassy/embassy" }
#embassy-stm32 = { path = "../../../../../embassy/embassy-stm32" }

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 's'
overflow-checks = false
