[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "drogue-temperature"
description = "Application reporting temperature data to Drogue Cloud"
version = "0.1.0"
keywords = ["ignore"]

[dependencies]
embassy = { version = "0.1.0", default-features = false, features = ["time"] }
drogue-device = { path = "../../../device", default-features = false }
embedded-hal = { version = "0.2", features = ["unproven"] }
defmt = { version = "0.3", optional = true }
log = { version = "0.4", optional = true }
heapless = "0.7"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-json-core = { version = "0.4", default-features = false, features = ["heapless"] }
drogue-tls = { version = "0.5.0", default-features = false, features = ["async"], optional = true}
rand_core = { version = "0.6.2", default-features = false }
embedded-hal-1 = { package = "embedded-hal", version = "1.0.0-alpha.7", git = "https://github.com/embassy-rs/embedded-hal", branch = "embassy2" }
embedded-hal-async = { version = "0.0.1", git = "https://github.com/embassy-rs/embedded-hal", branch = "embassy2" }
embedded-nal-async = "0.1.0"

[features]
default = ["std"]
tls = ["drogue-tls", "drogue-device/tls"]
std = ["serde-json-core/std", "embassy/std"]
